import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, CircleAlert, ExternalLink, Lightbulb } from 'lucide-react';
import SEO from '../components/SEO';
import NotFound from './NotFound';
import { getPracticalGuide, practicalGuides } from '../data/practicalGuides';
import './Guides.css';

const StudioFigure = () => <figure className="guides-studio-figure">
  <a href="/assets/guides/studio-crop.png" target="_blank" rel="noreferrer"><img src="/assets/guides/studio-crop.png" width="1280" height="743" loading="lazy" alt="Interface du Studio FormaPrompt montrant les quatre composantes CROP et leur pondération dans le score pédagogique." /></a>
  <figcaption>Le Studio présente les composantes CROP et leur pondération. Son score est un repère pédagogique local : il ne génère pas de réponse IA et ne valide ni les faits ni la conformité.</figcaption>
</figure>;

function CropDiagram() {
  const items = [['C', 'Contexte', 'Pour qui, dans quelle situation, avec quelles informations autorisées ?'], ['R', 'Rôle', 'Quelle expertise ou posture doit guider la réponse ?'], ['O', 'Objectif', 'Quel livrable concret doit être obtenu ?'], ['P', 'Précisions', 'Format, contraintes, sources, exclusions et contrôles.']];
  return <div className="guides-crop-diagram" role="list" aria-label="Les quatre composantes de la méthode CROP">{items.map(([letter, title, text]) => <div role="listitem" key={letter}><strong>{letter}</strong><span><b>{title}</b>{text}</span></div>)}</div>;
}

function StudioCallout() {
  return <aside className="guides-callout guides-callout-studio"><Lightbulb aria-hidden="true" /><div><h2>Préparer sans transmettre</h2><p>Le <Link to="/studio/">Studio FormaPrompt</Link> aide à clarifier une demande et ses contraintes. Son diagnostic est déterministe et local : il ne remplace pas la vérification humaine. N’y saisissez pas de données personnelles ou confidentielles.</p></div></aside>;
}

function BeginnerGuide() {
  return <>
    <p className="guides-lead">L’IA générative produit du texte, une image, un résumé, un plan ou du code à partir d’une consigne. Elle peut faire gagner du temps au démarrage d’une tâche. Elle ne remplace ni la connaissance du métier, ni la vérification finale.</p>
    <section id="comprendre"><h2>Ce que l’outil peut faire — et ce qu’il ne fait pas</h2><p>Une IA générative repère des régularités et propose une réponse plausible. Elle ne contrôle pas spontanément la véracité de chaque phrase, ne connaît pas votre organisation et ne décide pas à votre place.</p><p>Une réponse claire peut donc contenir une date erronée, une source inexistante ou une règle mal comprise. Son rôle raisonnable : préparer une première version, explorer des formulations ou structurer une idée à contrôler.</p></section>
    <section id="premier-essai"><h2>Un premier essai, sans se mettre en difficulté</h2><p>Choisissez une tâche sans donnée sensible dont vous connaissez déjà le résultat attendu : reformuler un message, préparer le plan d’une réunion ou proposer des titres de support.</p><div className="guides-before-after"><div><p className="guides-panel-label">Demande vague</p><p>« Fais-moi un texte sur les mots de passe. »</p></div><div><p className="guides-panel-label">Demande exploitable</p><p>« Prépare le plan d’une séquence de 30 minutes sur les mots de passe robustes, pour des adultes débutants. Je veux un objectif, une activité courte, trois messages essentiels et une vérification finale. N’invente pas de statistiques ni de règles juridiques. »</p></div></div><ol className="guides-steps"><li><b>Nommer le résultat attendu.</b> Indiquez le document à produire.</li><li><b>Donner le contexte utile.</b> Public, niveau, but et contraintes changent la réponse.</li><li><b>Demander un format.</b> Tableau, plan, mail ou fiche évitent une réponse vague.</li><li><b>Relire avant usage.</b> Contrôlez faits, sources, ton et confidentialité.</li></ol></section>
    <section id="precautions"><h2>Les précautions à garder dès le premier essai</h2><p>Ne copiez pas dans un outil grand public des données personnelles, de santé, d’évaluation, de paie, contractuelles ou confidentielles sans cadre validé. Le RGPD et la confidentialité continuent de s’appliquer.</p><p>Pour une information récente, réglementaire, financière, médicale ou technique, demandez des sources puis consultez les sources primaires. Ne vous contentez pas d’un lien qui a l’air crédible. Pour une production destinée à un apprenant, un client ou au public, une relecture humaine reste nécessaire.</p></section>
    <StudioFigure /><StudioCallout />
    <p className="guides-training-link">Pour aller plus loin sur les usages concrets et responsables, découvrez la <Link to="/formation-ia-generative">formation IA générative</Link>.</p>
  </>;
}

function PromptGuide() {
  return <>
    <p className="guides-lead">Le prompt engineering n’est pas la recherche d’une formule secrète. Au travail, il consiste surtout à transformer un besoin imprécis en une consigne que l’on peut relire, tester et améliorer.</p>
    <section id="crop"><h2>La méthode CROP : contexte, rôle, objectif, précisions</h2><p>« Prépare une formation sur l’IA » ne précise ni le public, ni le temps disponible, ni le livrable. L’IA devra deviner et proposera souvent un contenu générique.</p><CropDiagram /><div className="guides-before-after"><div><p className="guides-panel-label">Avant</p><p>« Prépare une formation sur l’IA. »</p></div><div><p className="guides-panel-label">Après : CROP</p><p><b>Contexte :</b> séance en présentiel pour huit salariés administratifs débutants.<br /><b>Rôle :</b> formateur en outils numériques habitué à ce public.<br /><b>Objectif :</b> déroulé de 1 h 30 dans un tableau.<br /><b>Précisions :</b> deux exercices sans données réelles, un temps de relecture, français simple, aucune source inventée.</p></div></div><p>La méthode ne garantit pas une bonne réponse. Elle rend la demande discutable : durée réaliste, exercices adaptés, contenus à exclure et critères de contrôle.</p></section>
    <p>Objectif pédagogique : obtenir un déroulé de 1 h 30 dans un tableau, pour apprendre à rédiger une demande utile et à repérer une réponse non vérifiée.</p><section id="deux-temps"><h2>Travailler en deux temps</h2><div className="guides-flow" aria-label="Processus de travail en deux temps"><div><span>1</span><b>Cadrer et vérifier</b><p>Demandez un plan ou les questions manquantes, puis contrôlez le cadre.</p></div><ArrowRight aria-hidden="true" /><div><span>2</span><b>Rédiger et améliorer</b><p>Demandez une version, corrigez un écart précis, puis comparez.</p></div></div><p>Cette méthode évite de corriger un long texte dont la direction était fausse dès le départ. Elle est utile pour les supports de formation, procédures, réponses clients et synthèses.</p></section>
    <section id="controles"><h2>Cinq contrôles avant de réutiliser une réponse</h2><ul className="guides-check-list"><li><Check /> Les faits, dates, chiffres et citations renvoient à une source consultée.</li><li><Check /> Les exemples correspondent au public et à l’organisation, ils ne sont pas inventés.</li><li><Check /> Aucune donnée personnelle, sensible ou confidentielle n’a été transmise inutilement.</li><li><Check /> Le document respecte durée, ton, réglementation et niveau pédagogique.</li><li><Check /> Une personne compétente assume le résultat et ses conséquences.</li></ul></section>
    <StudioFigure /><StudioCallout />
    <p className="guides-training-link">La <Link to="/formation-prompt-engineering">formation Prompt Engineering</Link> permet ensuite de travailler les exemples, itérations et contrôles sur des cas professionnels. Retrouvez aussi les ressources publiées sur le <Link to="/blog">blog FormaPrompt</Link>.</p>
  </>;
}

function AiActGuide() {
  const checks = ['Recenser chaque usage : outil, fournisseur, finalité, équipe, personnes concernées et date de revue.', 'Décrire les données : personnelles, sensibles, confidentielles, pédagogiques ou anonymisées. Éviter toute transmission non nécessaire.', 'Repérer les décisions sur des personnes : admission, positionnement, évaluation, orientation ou décision influencée par un outil.', 'Écarter les pratiques interdites : examiner l’article 5 ; en cas de doute sur un usage, interrompre le projet et demander un avis qualifié.', 'Organiser la littératie IA selon le rôle, l’expérience et les risques : limites, données, biais, signalement et supervision humaine.', 'Conserver une preuve proportionnée : support, participants, règles internes et date de révision.', 'Vérifier la transparence : examiner l’article 50 pour un chatbot ou certains contenus produits avec l’IA.', 'Maintenir la décision humaine : qui relit, corrige, tranche et organise un réexamen ?', 'Articuler AI Act et RGPD : finalité, base légale, minimisation, information, sécurité, conservation et droits.', 'Vérifier contrats et réglages : traitement des données, accès, transferts, conservation et sous-traitants.'];
  return <>
    <p className="guides-lead">Cette checklist ne remplace ni une analyse juridique ni un audit de conformité. Elle aide à examiner des usages réels : supports, assistant conversationnel, correction assistée, orientation ou automatisation administrative.</p>
    <section id="checklist"><h2>Checklist de départ</h2><p>Le règlement européen sur l’intelligence artificielle s’applique progressivement. L’article 4 est applicable depuis le 2 février 2025. Il demande aux fournisseurs et déployeurs de soutenir le développement de la littératie IA de leurs équipes et des personnes qui utilisent ces systèmes pour leur compte.</p><p>Les mesures doivent tenir compte du contexte et des personnes concernées. La Commission indique qu’il ne s’agit pas de mesurer le niveau de chaque salarié ni d’obtenir un certificat : une trace interne des actions peut être conservée.</p><div className="guides-ai-flow" aria-label="Démarche de revue des usages IA"><span>Usage réel</span><ArrowRight aria-hidden="true" /><span>Données et personnes</span><ArrowRight aria-hidden="true" /><span>Risques et règles</span><ArrowRight aria-hidden="true" /><span>Mesures et revue</span></div><ul className="guides-check-list guides-checklist-interactive">{checks.map((check) => <li key={check}><span className="guides-box" aria-hidden="true" /><span>{check}</span></li>)}</ul><p className="guides-source-note"><ExternalLink size={16} /> Sources officielles : <a href="https://eur-lex.europa.eu/eli/reg/2024/1689/2026-07-27/eng" target="_blank" rel="noreferrer">règlement (UE) 2024/1689 sur EUR-Lex</a> et <a href="https://digital-strategy.ec.europa.eu/en/faqs/ai-literacy-questions-answers" target="_blank" rel="noreferrer">questions-réponses de la Commission européenne</a>.</p></section>
    <section id="situations"><h2>Trois situations à distinguer</h2><div className="guides-situation-grid"><article><h3>Support de cours générique</h3><p>Le risque est souvent plus limité. La vérification pédagogique et factuelle reste nécessaire.</p></article><article><h3>Assistant pour les apprenants</h3><p>Définissez ses réponses, informez les utilisateurs, prévoyez un relais humain et protégez les données.</p></article><article><h3>Évaluer ou orienter une personne</h3><p>Analysez précisément l’usage, les conséquences, le contrôle humain et les obligations applicables.</p></article></div></section>
    <section id="limites"><h2>Ce que cette démarche ne permet pas d’affirmer</h2><p>Cocher ces points ne permet pas de déclarer un organisme « conforme AI Act ». Cela ne vaut ni certification, ni audit juridique, ni garantie pour un dispositif à risque élevé. La qualification dépend de l’outil, de son rôle, des personnes concernées et des textes applicables.</p><aside className="guides-callout guides-callout-warning"><CircleAlert aria-hidden="true" /><div><h3>Point de vigilance</h3><p>Ce guide est une ressource pédagogique. Pour un cas sensible, une qualification de risque ou une décision de déploiement, faites vérifier la situation par les personnes compétentes.</p></div></aside><p>Un premier résultat concret peut être plus simple : un registre des usages daté, une règle sur les données, un parcours de littératie adapté et un responsable de revue identifié. Retrouvez les ressources publiées sur le <Link to="/blog">blog FormaPrompt</Link> et découvrez la <Link to="/formation-ia-act-conformite">formation IA Act et conformité</Link> pour travailler les usages et les compétences.</p></section>
    <StudioCallout />
  </>;
}

function contentFor(slug) { if (slug === 'ia-generative-debutants') return <BeginnerGuide />; if (slug === 'prompt-engineering-professionnel-methode') return <PromptGuide />; return <AiActGuide />; }

export default function GuidePage() {
  const { slug } = useParams();
  const guide = getPracticalGuide(slug);
  if (!guide) return <NotFound />;
  const canonicalUrl = `https://formaprompt.com/guides/${guide.slug}`;
  const jsonLd = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'Article', headline: guide.title, description: guide.description, inLanguage: 'fr-FR', mainEntityOfPage: canonicalUrl, author: { '@type': 'Person', name: 'Thierry FREZARD' }, publisher: { '@type': 'Organization', name: 'FormaPrompt' } },
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Accueil', item: 'https://formaprompt.com/' }, { '@type': 'ListItem', position: 2, name: 'Guides', item: 'https://formaprompt.com/guides' }, { '@type': 'ListItem', position: 3, name: guide.title, item: canonicalUrl }] },
  ] };
  const related = practicalGuides.filter((item) => item.slug !== guide.slug);
  return <div className="guides-page">
    <SEO title={`${guide.title} – FormaPrompt`} description={guide.description} url={canonicalUrl} type="article" jsonLd={jsonLd} />
    <section className="guides-article-hero"><div className="container"><Link className="guides-back-link" to="/guides"><ArrowLeft size={17} /> Tous les guides</Link><p className="guides-tag">{guide.label} · {guide.readingTime}</p><h1>{guide.title}</h1><p>{guide.description}</p></div></section>
    <div className="container guides-article-layout"><aside className="guides-toc" aria-label="Sommaire"><p>Dans ce guide</p><ol>{guide.sections.map((section) => <li key={section.id}><a href={`#${section.id}`}>{section.label}</a></li>)}</ol></aside><article className="guides-article-content">{contentFor(guide.slug)}<section className="guides-next" aria-labelledby="guides-next-title"><h2 id="guides-next-title">Continuer avec</h2><div>{related.map((item) => <Link key={item.slug} to={`/guides/${item.slug}`}>{item.title}<ArrowRight size={17} /></Link>)}</div></section></article></div>
  </div>;
}
